# to do: make size of the mall map dependent on NameMall.Mall() characteristics
#add stores
print('/////////////////////////////////////////////')
print('/                                           /')
print('/                                           /')
print('/                                           /')
print('/                                           /')
print('/                                           /')
print('/                                           /')
print('/                                           /')
print('/                                           /')
print('/                                           /')
print('/                                           /')
print('/                                           /')
print('/                                           /')
print('/                                           /')
print('/                                           /')
print('/////////////////////////////////////////////')
